#!/bin/bash

set -e

source script/configure

for app in $apps; do
  _app=$(basename $app)
  if [[ ! -d $WORK/$_app ]] ; then
    echo "Installing: ${app}"
    git clone git@github.com:$app.git $WORK/$_app
  else 
    echo "Not updating local copy of ${app}"
  fi
done
